# Generated by Django 4.2.4 on 2023-08-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titlte',
            new_name='title',
        ),
    ]
